name = "Inheritance"
author = "Lee Clark"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "b06cd660ffc9e304105d3c4b827bc7389daf18476ff9efc2663c6973b2468c49"

[versions]
forge = "47.2.19"
minecraft = "1.20.1"
