name = "Inheritance"
author = "Lee Clark"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "deb7e85762878db758f253df954ba04c85cf849073399fb0ffe0368a9a8085f1"

[versions]
forge = "47.2.19"
minecraft = "1.20.1"
