name = "Inheritance"
author = "Lee Clark"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "698a1dc2de2dbc32e3261c7c385518f4e51a234eb07778c09f8559b4fdca52b9"

[versions]
forge = "47.2.19"
minecraft = "1.20.1"
